# Generated by Django 4.1.7 on 2023-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('parent_id', models.IntegerField(verbose_name='parent id fiel')),
                ('parent_id_user', models.IntegerField(verbose_name='parent id user')),
                ('type_model', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MoreVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='otp_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_code', models.IntegerField()),
                ('time_code', models.DateTimeField()),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('poster', models.ImageField(upload_to='posts/poster_images/', verbose_name='Poster')),
                ('content', models.CharField(max_length=2000, verbose_name='Content')),
                ('publish_time', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('views', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=150, verbose_name='Titel')),
                ('content', models.CharField(max_length=500, verbose_name='Content')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
            ],
        ),
    ]
