# Generated by Django 4.1.7 on 2023-02-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auther_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='post',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Auther', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otp_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='morevideopost',
            name='post_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post1', to='posts.post'),
        ),
        migrations.AddField(
            model_name='morevideopost',
            name='post_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post2', to='posts.post'),
        ),
        migrations.AddField(
            model_name='morevideopost',
            name='video_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video1', to='posts.video'),
        ),
        migrations.AddField(
            model_name='morevideopost',
            name='video_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video2', to='posts.video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auhter_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
